# Site settings
title: Diana Ruth - Blog
description:
baseurl: "/blog"
url: "https://dianaruth.github.io"
github_username: dianaruth

# Build settings
markdown: kramdown
#markdown: redcarpet
paginate: 5
paginate_path: '/posts/page:num/'
gems: ['jekyll-paginate']
