# Site settings
title: Diana Ruth - Blog
description: 
baseurl: ""
url: ""
github_username: dianaruth

# Build settings
markdown: kramdown
#markdown: redcarpet
paginate: 5
paginate_path: '/posts/page:num/'
gems: ['jekyll-paginate']
